name: cyan
description: "Decentralized Collaborative Whiteboarding - UI for XaeroFlux"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Reactive Programming (for UI event streams only)
  rxdart: ^0.27.7

  # Navigation
  go_router: ^12.1.3

  # FFI for XaeroFlux Integration
  ffi: ^2.1.0

  # UI Components
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6

  # Image Capture for AI Digitization
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1

  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

  # Testing
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  # Assets for UI only (uncomment when you add the files)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts for Monokai Theme (uncomment when you add the font files)
  # fonts:
  #   - family: JetBrainsMono
  #     fonts:
  #       - asset: assets/fonts/JetBrainsMono-Regular.ttf
  #       - asset: assets/fonts/JetBrainsMono-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

  # Uncomment when you add splash screen image
  # flutter_native_splash:
  #   color: "#272822"
  #   image: assets/images/cyan_logo.png
